import type { Node, Edge } from '@xyflow/svelte';
import type { HttpTriggerData, CodeBlockData, ConditionalData, FetchNodeData, DataStoreData, HttpResponseData } from '../types';

export function generateSvelteKitCode(nodes: Node[], edges: Edge[]): string {
	const trigger = nodes.find((n: Node) => n.type === 'httpTrigger');
	const method = (((trigger?.data as any)?.method || 'POST') as string).toUpperCase();
	const path = ((trigger?.data as any)?.path || '/api/endpoint') as string;

	let code = `import { json, type RequestHandler } from '@sveltejs/kit';

/**
 * Auto-generated by Nodely API Visual Builder
 * Endpoint: ${method} ${path}
 */

// In-memory collection storage (replace with your preferred database or ORM)
const store: Record<string, Record<string, any>> = {};

export const ${method}: RequestHandler = async ({ request, url }) => {
	try {
		// 1. Extract request payload and query params
		let payload: any = {};
		if (request.method !== 'GET') {
			try {
				payload = await request.json();
			} catch {
				payload = {};
			}
		}
		const query = Object.fromEntries(url.searchParams.entries());
		const headers = Object.fromEntries(request.headers.entries());
		const state: Record<string, any> = {};

`;

	// Walk from trigger
	let current: Node | undefined = trigger;
	let stepNum = 2;
	const visited = new Set<string>();

	while (current && !visited.has(current.id)) {
		visited.add(current.id);
		const nodeData = (current.data || {}) as any;
		const nextEdges = edges.filter((e: Edge) => e.source === current?.id);

		if (current.type === 'codeBlock') {
			const blockData = nodeData as CodeBlockData;
			code += `\t\t// ${stepNum}. Code Block: ${blockData.title || 'Transform'}\n`;
			code += `\t\tstate['${current.id}'] = await (async () => {\n`;
			const indentedCode = (blockData.code || 'return payload;')
				.split('\n')
				.map((line: string) => `\t\t\t${line}`)
				.join('\n');
			code += `${indentedCode}\n`;
			code += `\t\t})();\n\n`;
			stepNum++;
			current = nodes.find((n: Node) => n.id === nextEdges[0]?.target);
		} else if (current.type === 'conditional') {
			const condData = nodeData as ConditionalData;
			const trueEdge = nextEdges.find((e: Edge) => e.sourceHandle === 'true');
			const falseEdge = nextEdges.find((e: Edge) => e.sourceHandle === 'false');
			const trueNode = nodes.find((n: Node) => n.id === trueEdge?.target);
			const falseNode = nodes.find((n: Node) => n.id === falseEdge?.target);

			code += `\t\t// ${stepNum}. Conditional Branching: ${condData.title || 'Check condition'}\n`;
			code += `\t\tconst conditionMet = Boolean(${condData.expression || 'true'});\n`;
			code += `\t\tif (conditionMet) {\n`;
			if (trueNode && trueNode.type === 'httpResponse') {
				const respData = trueNode.data as unknown as HttpResponseData;
				code += `\t\t\treturn json(${respData.bodyExpression || 'payload'}, { status: ${respData.statusCode || 200} });\n`;
			} else {
				code += `\t\t\t// Continue along TRUE branch\n`;
			}
			code += `\t\t} else {\n`;
			if (falseNode && falseNode.type === 'httpResponse') {
				const respData = falseNode.data as unknown as HttpResponseData;
				code += `\t\t\treturn json(${respData.bodyExpression || '{ error: "Condition failed" }'}, { status: ${respData.statusCode || 400} });\n`;
			} else {
				code += `\t\t\t// Continue along FALSE branch\n`;
			}
			code += `\t\t}\n\n`;
			stepNum++;
			current = undefined;
		} else if (current.type === 'fetchNode') {
			const fetchData = nodeData as FetchNodeData;
			code += `\t\t// ${stepNum}. External Fetch: ${fetchData.title || 'API Request'}\n`;
			code += `\t\tconst fetchRes = await fetch('${fetchData.url || ''}', {\n`;
			code += `\t\t\tmethod: '${fetchData.method || 'GET'}',\n`;
			code += `\t\t\theaders: { 'Content-Type': 'application/json' }\n`;
			code += `\t\t});\n`;
			code += `\t\tstate['${current.id}'] = await fetchRes.json();\n\n`;
			stepNum++;
			current = nodes.find((n: Node) => n.id === nextEdges[0]?.target);
		} else if (current.type === 'dataStore') {
			const storeData = nodeData as DataStoreData;
			code += `\t\t// ${stepNum}. Data Store: ${storeData.title || 'DB Operation'}\n`;
			code += `\t\tif (!store['${storeData.collection}']) store['${storeData.collection}'] = {};\n`;
			if (storeData.operation === 'set') {
				code += `\t\tstore['${storeData.collection}'][${storeData.keyExpr || '""'}] = ${storeData.valueExpr || 'payload'};\n`;
			} else if (storeData.operation === 'get') {
				code += `\t\tstate['${current.id}'] = store['${storeData.collection}'][${storeData.keyExpr || '""'}];\n`;
			}
			code += `\n`;
			stepNum++;
			current = nodes.find((n: Node) => n.id === nextEdges[0]?.target);
		} else if (current.type === 'httpResponse') {
			const respData = nodeData as HttpResponseData;
			code += `\t\t// Final Response: HTTP ${respData.statusCode || 200}\n`;
			code += `\t\treturn json(${respData.bodyExpression || 'payload'}, { status: ${respData.statusCode || 200} });\n`;
			current = undefined;
		} else {
			current = nodes.find((n: Node) => n.id === nextEdges[0]?.target);
		}
	}

	code += `\t} catch (err: any) {\n`;
	code += `\t\treturn json({ error: err.message || 'Internal Server Error' }, { status: 500 });\n`;
	code += `\t}\n`;
	code += `};\n`;

	return code;
}

export function generateExpressCode(nodes: Node[], edges: Edge[]): string {
	const trigger = nodes.find((n: Node) => n.type === 'httpTrigger');
	const method = (((trigger?.data as any)?.method || 'post') as string).toLowerCase();
	const path = ((trigger?.data as any)?.path || '/api/endpoint') as string;

	return `import express from 'express';

const app = express();
app.use(express.json());

// Generated by Nodely
app.${method}('${path}', async (req, res) => {
	try {
		const payload = req.body;
		const query = req.query;
		const state = {};

		// Execute flow steps
		return res.status(200).json({ success: true, payload });
	} catch (err: any) {
		return res.status(500).json({ error: err.message });
	}
});

export default app;
`;
}
